source "http://rubygems.org"

require 'rbconfig'

group :development do

  gem 'rake'
  gem 'guard'
  gem 'rb-fsevent'
  gem 'rb-inotify'

  gem 'execjs', '~> 1.4.0'
  gem 'therubyracer', :platforms => [:ruby] # v8 engine  

  gem 'sass', '3.1.5'
  gem 'guard-sass'

  # gem 'guard-sprockets', '0.4.3'
  gem 'guard-sprockets', :git => 'git://github.com/mcavallo/guard-sprockets.git'
  # gem 'guard-sprockets', :path => '/home/mariano/Dev/Repos/guard-sprockets'

  gem 'guard-process'
  gem 'guard-livereload'

  gem 'uglifier'
  gem 'juicer'
  gem 'guard-uglify'
  
  gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw/i
  
end